const countries = {
  "de-DE": "Deutsch",
  "en-US": "US English",
  "en-GB": "UK English Female",
  "en-GB": "UK English Male",
  "es-ES": "español",
  "es-US": "español de Estados Unidos",
  "fr-FR": "français",
  "hi-IN": "हिन्दी Hindi",
  "id-ID": "Bahasa Indonesia",
  "it-IT": "italiano",
  "ja-JP": "日本語",
  "ko-KR": "한국의",
  "nl-NL": "Nederlands",
  "pl-PL": "polski",
  "pt-BR": "português do Brasil",
  "ru-RU": "русский",
  "zh-CN": "​普通话（中国大陆）",
  "zh-HK": "​粤語（香港）",
  "zh-TW": "國語（臺灣）",
};
